// Code generated by "stringer -type=Err -trimprefix=Err"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNotFound-1]
	_ = x[ErrAlreadyExists-2]
	_ = x[ErrInvalidInput-3]
}

const _Err_name = "NotFoundAlreadyExistsInvalidInput"

var _Err_index = [...]uint8{0, 8, 21, 33}

func (i Err) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Err_index)-1 {
		return "Err(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Err_name[_Err_index[idx]:_Err_index[idx+1]]
}
