// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conversation/v1/conversation.proto

package conversationV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_conversation_v1_conversation_proto protoreflect.FileDescriptor

const file_conversation_v1_conversation_proto_rawDesc = "" +
	"\n" +
	"\"conversation/v1/conversation.proto\x12\x0fconversation.v1BMZKgithub.com/zhmlst/assistant/conversation/pkg/conversation/v1;conversationV1b\x06proto3"

var file_conversation_v1_conversation_proto_goTypes = []any{}
var file_conversation_v1_conversation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_conversation_v1_conversation_proto_init() }
func file_conversation_v1_conversation_proto_init() {
	if File_conversation_v1_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_v1_conversation_proto_rawDesc), len(file_conversation_v1_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conversation_v1_conversation_proto_goTypes,
		DependencyIndexes: file_conversation_v1_conversation_proto_depIdxs,
	}.Build()
	File_conversation_v1_conversation_proto = out.File
	file_conversation_v1_conversation_proto_goTypes = nil
	file_conversation_v1_conversation_proto_depIdxs = nil
}
